---
- name: Create volumes on Nectar
  os_volume:
   display_name: '{{ item.vol_name }}'
   size: '{{ item.vol_size }}'
   availability_zone: '{{ availability_zone }}'
   wait: yes
   timeout: 600
   state: present
  loop: '{{ volumes }}'
  register: os_vol

- name: Variable for volume id
  set_fact:
   os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
   msg: "volume {{ os_vol_ids }} has been created"
#
#- debug:
#   msg: "this is the first index {{ os_vol_ids[0] }} okay"
