---
# Title: The Seven Deadly Sins in Social Media Case Study in Victoria Cities
# Team Name: Team 14
# Team Members:
#   Dading Zainal Gusti (1001261)
#   David Setyanugraha (867585)
#   Ghawady Ehmaid (983899)
#   Indah Permatasari (929578)
#   Try Ajitiono (990633)
- name: copy py scripts
  copy:
   src: harvest
   dest: /home/ubuntu/
   mode: +x

- name: create vic db
  uri:
    url: http://localhost:5984/victoria
    user: admin
    password: password
    method: PUT
    force_basic_auth: yes
    status_code: 200,201,412
#  when: inventory_hostname == groups['remote'][0]

- name: node 1 run harvest bk1
  shell: nohup python3 -u /home/ubuntu/harvest/harvest-bk1.py > /home/ubuntu/harvest/bk1.log &
  async: 2592000
  poll: 0
  when: inventory_hostname == groups['remote'][0]

- name: node 2 run harvest bk2
  shell: nohup python3 -u /home/ubuntu/harvest/harvest-bk2.py > /home/ubuntu/harvest/bk2.log &
  async: 2592000
  poll: 0
  when: inventory_hostname == groups['remote'][1]

- name: copy py scripts to node 3
  copy:
   src: analysis
   dest: /home/ubuntu/
   mode: +x
  when: inventory_hostname == groups['remote'][2]
