---
# Title: The Seven Deadly Sins in Social Media Case Study in Victoria Cities
# Team Name: Team 14
# Team Members:
#   Dading Zainal Gusti (1001261)
#   David Setyanugraha (867585)
#   Ghawady Ehmaid (983899)
#   Indah Permatasari (929578)
#   Try Ajitiono (990633)
- name: adding all nodes to remote group
  add_host:
   groups: remote
   name: '{{ item }}'
  loop: '{{ nodes_ips }}'
  register: remote_nodes

- name: Wait 10 seconds for port 22 to become open and contain OpenSSH
  wait_for:
    port: 22
    host: '{{ item }}'
    search_regex: OpenSSH
    delay: 10
  loop: '{{ nodes_ips }}'
