---
- name: setup nginx
  become: true
  # Relative to setup-remote-nginx role.
  template: src=nginx.conf.tpl
    dest=/etc/nginx/nginx.conf
  when: inventory_hostname == groups['remote'][0]

- name: restart nginx
  become: true
  service: name=nginx
    state=restarted
  when: inventory_hostname == groups['remote'][0]
