---
# Title: The Seven Deadly Sins in Social Media Case Study in Victoria Cities
# Team Name: Team 14
# Team Members:
#   Dading Zainal Gusti (1001261)
#   David Setyanugraha (867585)
#   Ghawady Ehmaid (983899)
#   Indah Permatasari (929578)
#   Try Ajitiono (990633)

- name: sudo apt-get update
  become: yes
  shell: apt-get update

- name: Install pip3
  become: yes
  apt:
   name: python3-pip
   state: present

- pause:
   seconds: 10
   prompt: let pip3 build cache

- name: install dependencies with pip3
  pip:
   name: '{{ item.dep_name }}'
   state: latest
   executable: pip3
  loop: '{{ pip_dep }}'
