---
# Title: The Seven Deadly Sins in Social Media Case Study in Victoria Cities
# Team Name: Team 14
# Team Members:
#   Dading Zainal Gusti (1001261)
#   David Setyanugraha (867585)
#   Ghawady Ehmaid (983899)
#   Indah Permatasari (929578)
#   Try Ajitiono (990633)
- name: Create instances
  os_server:
   name: '{{ item.0.node_name }}'
   image: '{{ instance_image }}'
   key_name: '{{ instance_key_name }}'
   flavor: '{{ instance_flavor }}'
   availability_zone: '{{ availability_zone }}'
   security_groups: '{{ sg_list }}'
   volumes: '{{ item.1.vol_name }}'
   network: qh2-uom-internal
   auto_floating_ip: yes
   wait: yes
   timeout: 600
   state: present  
  loop: '{{ nodes|zip(volumes)|list }}'
  register: created_nodes

- name: Variable for IPs
  set_fact:
   nodes_ips: '{{ nodes_ips|default([]) + [ item.openstack.public_v4 ] }}'
  loop: '{{ created_nodes.results }}'

- debug:
   msg: "remote hosts {{ nodes_ips }} are created"
