#nectar.yaml
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: build-common
    - role: build-volume
    - role: build-security-groups
    - role: build-instance
    - role: build-node-groups

- hosts: remote
  vars_files:
    - host_vars/nectar.yaml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: setup-remote-proxy
  vars:
    ansible_ssh_private_key_file: '~/cloudkey.pem'

- hosts: remote
  vars_files:
    - host_vars/nectar.yaml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: setup-remote-couchdb
    - role: setup-remote-nginx
    - role: setup-remote-dep
    - role: run-harvesters
  vars:
    ansible_ssh_private_key_file: '~/cloudkey.pem'

#- hosts: remote
#  vars_files:
#    - host_vars/nectar.yaml
#  remote_user: ubuntu
#  gather_facts: true
#  roles:
#    - role: run-harvesters
#  vars:
#    ansible_ssh_private_key_file: '~/cloudkey.pem'
