#nectar.yaml
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: build-common
    - role: build-volume
    - role: build-security-groups
    - role: build-instance
    - role: build-node-groups

#- name: Wait 10 seconds for port 22 to become open and contain OpenSSH
#  wait_for:
#    port: 22
#    host: remote
#    search_regex: OpenSSH
#    delay: 10

- hosts: remote
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: setup-remote-couchdb
  vars:
    ansible_ssh_private_key_file: '~/Downloads/dading-key.pem'
