# Title: The Seven Deadly Sins in Social Media Case Study in Victoria Cities
# Team Name: Team 14
# Team Members:
#   Dading Zainal Gusti (1001261)
#   David Setyanugraha (867585)
#   Ghawady Ehmaid (983899)
#   Indah Permatasari (929578)
#   Try Ajitiono (990633)
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: build-common
    - role: build-volume
    - role: build-security-groups
    - role: build-instance
    - role: build-node-groups

- hosts: remote
  vars_files:
    - host_vars/nectar.yaml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: setup-remote-proxy
  vars:
    ansible_ssh_private_key_file: '~/id_rsa'

- hosts: remote
  vars_files:
    - host_vars/nectar.yaml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: setup-remote-couchdb
    - role: setup-remote-nginx
    - role: setup-remote-dep
    - role: run-harvesters
  vars:
    ansible_ssh_private_key_file: '~/id_rsa'
